# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Welcome! &nbsp;  &nbsp;  |  &nbsp;  &nbsp;   স্বাগতম!
# Description of the Site
description: I wish I could write more about myself, but I don't want to ~_~
# URL of Image of the Site
site-image: /home/assets/images/blossom.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /home/assets/images/blossom.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: afia.afrin92@gmail.com
facebook_username: meghla1011
twitter_username: AfiaAfrin8
instagram_username: afiafrin_
linkedin_username: afia-afrin-251138138/
github_username:  afrin-afia
scholar_id: citations?user=0LLrL2gAAAAJ&hl=en&oi=ao
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Afia Afrin
# URL for the Image of the Author
author-image: /home/assets/images/aa.jpg
# 60 Words About the Author
author-about: Hi! I'm Afia. I am a first-year M.Sc. student at the University of Alberta. I earned a Bachelor of Science in Computer Science and Engineering in 2017 from Bangladesh University of Engineering and Technology.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/afrin-afia #https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
